version: 0.0.{build}
environment:
  TARGET: x86_64-pc-windows-msvc
#  matrix:
#  - TARGET: x86_64-pc-windows-msvc
#    PY: 2
#    PYTHONPATH: C:\Python27-x64
#    FEATURES: python27-sys
#  - TARGET: x86_64-pc-windows-msvc
#    PY: 3
#    PYTHONPATH: C:\Python34-x64
#    FEATURES: python3-sys
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - start /wait msiexec /i rust-nightly-%TARGET%.msi INSTALLDIR="%CD%\rust-nightly-%TARGET%" /quiet /qn /norestart
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - set PATH=%PATH%;%CD%/rust-nightly-%TARGET%/bin
  - SET PATH=%PYTHONPATH%;%PATH%
  - rustc -V
  - cargo -V
  - python --version
build_script:
 - set PATH=C:\Python27-x64;%PATH%&& cargo build --verbose --features python27-sys --no-default-features
 - set PATH=C:\Python34-x64;%PATH%&& cargo build --verbose --features python3-sys --no-default-features
test_script:
 - set PATH=C:\Python27-x64;%PATH%&& cargo test --verbose --features python27-sys --no-default-features
 - set PATH=C:\Python34-x64;%PATH%&& cargo test --verbose --features python3-sys --no-default-features
